version: '3.1'

services:

  db:
    image: mysql:8.0.31
    restart: always
    env_file:
      - ./root_db.env
      - ./common_db.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data: